![NYC Skyline](nyc.jpg)

Welcome to New York City, one of the most-visited cities in the world. There are many Airbnb listings in New York City to meet the high demand for temporary lodging for travelers, which can be anywhere between a few nights to many months. In this project, we will take a closer look at the New York Airbnb market by combining data from multiple file types like `.csv`, `.tsv`, and `.xlsx`.

Recall that **CSV**, **TSV**, and **Excel** files are three common formats for storing data. 
Three files containing data on 2019 Airbnb listings are available to you:

**data/airbnb_price.csv**
This is a CSV file containing data on Airbnb listing prices and locations.
- **`listing_id`**: unique identifier of listing
- **`price`**: nightly listing price in USD
- **`nbhood_full`**: name of borough and neighborhood where listing is located

**data/airbnb_room_type.xlsx**
This is an Excel file containing data on Airbnb listing descriptions and room types.
- **`listing_id`**: unique identifier of listing
- **`description`**: listing description
- **`room_type`**: Airbnb has three types of rooms: shared rooms, private rooms, and entire homes/apartments

**data/airbnb_last_review.tsv**
This is a TSV file containing data on Airbnb host names and review dates.
- **`listing_id`**: unique identifier of listing
- **`host_name`**: name of listing host
- **`last_review`**: date when the listing was last reviewed

In [38]:
# We've loaded your first package for you! You can add as many cells as you need.
import numpy as np
import pandas as pd

# Reading in data
price = pd.read_csv("data/airbnb_price.csv")
room = pd.read_excel("data/airbnb_room_type.xlsx")
review = pd.read_table("data/airbnb_last_review.tsv")

In [53]:
# Seeing price df
print(price.head())

   listing_id        price                nbhood_full
0        2595  225 dollars         Manhattan, Midtown
1        3831   89 dollars     Brooklyn, Clinton Hill
2        5099  200 dollars     Manhattan, Murray Hill
3        5178   79 dollars  Manhattan, Hell's Kitchen
4        5238  150 dollars       Manhattan, Chinatown

In [54]:
# Seeing room df
print(room.head())

   listing_id                                description        room_type
0        2595                      Skylit Midtown Castle  Entire home/apt
1        3831            Cozy Entire Floor of Brownstone  Entire home/apt
2        5099  Large Cozy 1 BR Apartment In Midtown East  Entire home/apt
3        5178            Large Furnished Room Near B'way     private room
4        5238         Cute & Cozy Lower East Side 1 bdrm  Entire home/apt

In [55]:
# Seeing review df
print(review.head())

   listing_id    host_name   last_review
0        2595     Jennifer   May 21 2019
1        3831  LisaRoxanne  July 05 2019
2        5099        Chris  June 22 2019
3        5178     Shunichi  June 24 2019
4        5238          Ben  June 09 2019

In [56]:
# Joining all dataframes
listings = pd.merge(price, room, on='listing_id')
listings = pd.merge(listings, review, on='listing_id')
print(listings.info())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 25209 entries, 0 to 25208
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   listing_id   25209 non-null  int64
 1   price        25209 non-null  object
 2   nbhood_full  25209 non-null  object
 3   description  25199 non-null  object
 4   room_type    25209 non-null  object
 5   host_name    25201 non-null  object
 6   last_review  25209 non-null  object
dtypes: int64(1), object(6)
memory usage: 1.5+ MB
None

In [57]:
# Changing last_review_data to datetime type
listings['last_review_date'] = pd.to_datetime(listings['last_review'], format='%B %d %Y')
print(listings.head())

   listing_id        price  ...   last_review last_review_date
0        2595  225 dollars  ...   May 21 2019       2019-05-21
1        3831   89 dollars  ...  July 05 2019       2019-07-05
2        5099  200 dollars  ...  June 22 2019       2019-06-22
3        5178   79 dollars  ...  June 24 2019       2019-06-24
4        5238  150 dollars  ...  June 09 2019       2019-06-09

[5 rows x 8 columns]

In [58]:
# Finding the earliest and latest review dates
first_reviewed_value = listings['last_review_date'].min()
last_reviewed_value = listings['last_review_date'].max()

In [59]:
# Showing that room types are not standardized
print(listings['room_type'].unique())

['Entire home/apt' 'private room' 'Private room' 'entire home/apt'
 'PRIVATE ROOM' 'shared room' 'ENTIRE HOME/APT' 'Shared room'
 'SHARED ROOM']

In [60]:
# Standardizing room types
listings['room_type_cleaned'] = listings['room_type'].str.lower()
print(listings['room_type_cleaned'].unique())

['entire home/apt' 'private room' 'shared room']

In [61]:
# Counting number of private rooms
number_private_rooms = listings['room_type_cleaned'].value_counts().loc['private room']
print(number_private_rooms)

11356

In [62]:
# Calculating average room price
listings['price_cleaned'] = listings['price'].str.replace(' dollars', '').astype(float)
average_price = listings['price_cleaned'].mean()
print(average_price)

141.7779364512674

In [63]:
# Creating dataframe encompassing all findings
d = {
    'first_reviewed': [first_reviewed_value],
    'last_reviewed': [last_reviewed_value],
    'nb_private_rooms': [number_private_rooms],
    'avg_price': [round(average_price,2)]
}
review_dates = pd.DataFrame(data=d)
print(review_dates)

  first_reviewed last_reviewed  nb_private_rooms  avg_price
0     2019-01-01    2019-07-09             11356     141.78